services:
  database:
    container_name: crm-db
    image: postgres:14
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"